version: '3.8'

services:
  flask-api:
    build: .
    container_name: flask-predict-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    command: python app.py
